import { Meta, StoryObj } from '@storybook/react';
import React from 'react';
import {
  useFilteredInstruments,
  AssetListItem,
  MarginListItem,
  MarketsList,
} from '@apex-rn/library/features/Markets';

const data = [
  {
    AllowOnlyMarketMakerCounterParty: false,
    AskOrderCt: 0,
    AskQty: 0.16898882,
    BestBid: 27399.73,
    BestOffer: 27400.37,
    BidOrderCt: 0,
    BidQty: 1.93391017,
    CreateWithMarketRunning: true,
    CurrentDayNotional: 32276425.432764,
    CurrentDayNumTrades: 4705,
    CurrentDayPxChange: -2.24,
    CurrentDayVolume: 1181.0464,
    InstrumentId: 1,
    InstrumentType: 'Standard',
    IsDisable: false,
    LastTradeTime: 1684403209711,
    LastTradedPx: 27399.73,
    LastTradedQty: 0.4702,
    MasterDataId: 0,
    MinimumPrice: 0.01,
    MinimumQuantity: 1e-8,
    OMSId: 1,
    OtcConvertSizeEnabled: false,
    OtcConvertSizeThreshold: 0,
    OtcTradesPublic: true,
    PreviousSessionStatus: 'Unknown',
    PriceCeilingLimit: 0,
    PriceCeilingLimitEnabled: false,
    PriceCollarConvertToOtcAccountId: 0,
    PriceCollarConvertToOtcClientUserId: 0,
    PriceCollarConvertToOtcEnabled: false,
    PriceCollarConvertToOtcThreshold: 0,
    PriceCollarEnabled: false,
    PriceCollarIndexDifference: 0,
    PriceCollarPercent: 0,
    PriceCollarThreshold: 0,
    PriceFloorLimit: 0,
    PriceFloorLimitEnabled: false,
    PriceIncrement: 0.01,
    PriceTier: 0,
    Product1: 2,
    Product1Symbol: 'BTC',
    Product1Name: 'Bitcoin',
    Product2: 1,
    Product2Symbol: 'USD',
    Product2Name: 'US Dollar',
    QuantityIncrement: 1e-8,
    Rolling24HrNotional: 78071787.496071,
    Rolling24HrPxChange: 535.16,
    Rolling24HrPxChangePercent: 1.9920661302228175,
    Rolling24HrVolume: 2876.8219,
    Rolling24NumTrades: 11492,
    SelfTradePrevention: true,
    SessionClose: 27399.73,
    SessionHigh: 27468.17,
    SessionLow: 27150.87,
    SessionOpen: 27401.97,
    SessionStatus: 'Running',
    SessionStatusDateTime: '2023-03-21T04:27:34.281Z',
    SortIndex: 0,
    Symbol: 'BTCUSD',
    TimeStamp: '1684403209721',
    VenueId: 1,
    VenueInstrumentId: 1,
    VenueSymbol: 'BTCUSD',
    Volume: 0.4702,
    MarginEnabled: true,
    MarginInitialRequirement: 0.5,
  },
  {
    AllowOnlyMarketMakerCounterParty: false,
    AskOrderCt: 0,
    AskQty: 0,
    BestBid: 16823.11,
    BestOffer: 0,
    BidOrderCt: 0,
    BidQty: 1,
    CreateWithMarketRunning: true,
    CurrentDayNotional: 0,
    CurrentDayNumTrades: 0,
    CurrentDayPxChange: 0,
    CurrentDayVolume: 0,
    InstrumentId: 2,
    InstrumentType: 'Standard',
    IsDisable: false,
    LastTradeTime: 0,
    LastTradedPx: 0,
    LastTradedQty: 0,
    MasterDataId: 0,
    MinimumPrice: 0.01,
    MinimumQuantity: 1e-8,
    OMSId: 1,
    OtcConvertSizeEnabled: false,
    OtcConvertSizeThreshold: 0,
    OtcTradesPublic: true,
    PreviousSessionStatus: 'Unknown',
    PriceCeilingLimit: 0,
    PriceCeilingLimitEnabled: false,
    PriceCollarConvertToOtcAccountId: 0,
    PriceCollarConvertToOtcClientUserId: 0,
    PriceCollarConvertToOtcEnabled: false,
    PriceCollarConvertToOtcThreshold: 0,
    PriceCollarEnabled: false,
    PriceCollarIndexDifference: 0,
    PriceCollarPercent: 0,
    PriceCollarThreshold: 0,
    PriceFloorLimit: 0,
    PriceFloorLimitEnabled: false,
    PriceIncrement: 0.01,
    PriceTier: 0,
    Product1: 3,
    Product1Symbol: 'ETH',
    Product1Name: 'Ethereum',
    Product2: 1,
    Product2Symbol: 'USD',
    Product2Name: 'US Dollar',
    QuantityIncrement: 1e-8,
    Rolling24HrNotional: 0,
    Rolling24HrPxChange: 0,
    Rolling24HrPxChangePercent: 0,
    Rolling24HrVolume: 0,
    Rolling24NumTrades: 0,
    SelfTradePrevention: true,
    SessionClose: 0,
    SessionHigh: 0,
    SessionLow: 0,
    SessionOpen: 0,
    SessionStatus: 'Running',
    SessionStatusDateTime: '2023-04-03T15:52:55.578Z',
    SortIndex: 0,
    Symbol: 'ETHUSD',
    TimeStamp: '0',
    VenueId: 1,
    VenueInstrumentId: 2,
    VenueSymbol: 'ETHUSD',
    Volume: 0,
    MarginEnabled: true,
    MarginInitialRequirement: 0.1,
  },
  {
    AllowOnlyMarketMakerCounterParty: false,
    AskOrderCt: 0,
    AskQty: 0,
    BestBid: 0,
    BestOffer: 0,
    BidOrderCt: 0,
    BidQty: 0,
    CreateWithMarketRunning: true,
    CurrentDayNotional: 0,
    CurrentDayNumTrades: 0,
    CurrentDayPxChange: 0,
    CurrentDayVolume: 0,
    InstrumentId: 3,
    InstrumentType: 'Standard',
    IsDisable: false,
    LastTradeTime: 0,
    LastTradedPx: 0,
    LastTradedQty: 0,
    MasterDataId: 0,
    MinimumPrice: 0.01,
    MinimumQuantity: 1e-8,
    OMSId: 1,
    OtcConvertSizeEnabled: false,
    OtcConvertSizeThreshold: 0,
    OtcTradesPublic: true,
    PreviousSessionStatus: 'Unknown',
    PriceCeilingLimit: 0,
    PriceCeilingLimitEnabled: false,
    PriceCollarConvertToOtcAccountId: 0,
    PriceCollarConvertToOtcClientUserId: 0,
    PriceCollarConvertToOtcEnabled: false,
    PriceCollarConvertToOtcThreshold: 0,
    PriceCollarEnabled: false,
    PriceCollarIndexDifference: 0,
    PriceCollarPercent: 0,
    PriceCollarThreshold: 0,
    PriceFloorLimit: 0,
    PriceFloorLimitEnabled: false,
    PriceIncrement: 0.01,
    PriceTier: 0,
    Product1: 6,
    Product1Symbol: 'THB',
    Product1Name: 'Thai Baht',
    Product2: 1,
    Product2Symbol: 'USD',
    Product2Name: 'US Dollar',
    QuantityIncrement: 1e-8,
    Rolling24HrNotional: 0,
    Rolling24HrPxChange: 0,
    Rolling24HrPxChangePercent: 0,
    Rolling24HrVolume: 0,
    Rolling24NumTrades: 0,
    SelfTradePrevention: true,
    SessionClose: 0,
    SessionHigh: 0,
    SessionLow: 0,
    SessionOpen: 0,
    SessionStatus: 'Running',
    SessionStatusDateTime: '2023-04-03T20:41:42.526Z',
    SortIndex: 0,
    Symbol: 'THBUSD',
    TimeStamp: '0',
    VenueId: 1,
    VenueInstrumentId: 3,
    VenueSymbol: 'THBUSD',
    Volume: 0,
    MarginEnabled: false,
    MarginInitialRequirement: 0,
  },
  {
    AllowOnlyMarketMakerCounterParty: false,
    AskOrderCt: 0,
    AskQty: 0,
    BestBid: 0,
    BestOffer: 0,
    BidOrderCt: 0,
    BidQty: 0,
    CreateWithMarketRunning: true,
    CurrentDayNotional: 0,
    CurrentDayNumTrades: 0,
    CurrentDayPxChange: 0,
    CurrentDayVolume: 0,
    InstrumentId: 4,
    InstrumentType: 'Standard',
    IsDisable: false,
    LastTradeTime: 0,
    LastTradedPx: 0,
    LastTradedQty: 0,
    MasterDataId: 0,
    MinimumPrice: 0.01,
    MinimumQuantity: 1e-8,
    OMSId: 1,
    OtcConvertSizeEnabled: false,
    OtcConvertSizeThreshold: 0,
    OtcTradesPublic: true,
    PreviousSessionStatus: 'Unknown',
    PriceCeilingLimit: 0,
    PriceCeilingLimitEnabled: false,
    PriceCollarConvertToOtcAccountId: 0,
    PriceCollarConvertToOtcClientUserId: 0,
    PriceCollarConvertToOtcEnabled: false,
    PriceCollarConvertToOtcThreshold: 0,
    PriceCollarEnabled: false,
    PriceCollarIndexDifference: 0,
    PriceCollarPercent: 0,
    PriceCollarThreshold: 0,
    PriceFloorLimit: 0,
    PriceFloorLimitEnabled: false,
    PriceIncrement: 0.01,
    PriceTier: 0,
    Product1: 4,
    Product1Symbol: 'OCN',
    Product1Name: 'Oil Coin',
    Product2: 1,
    Product2Symbol: 'USD',
    Product2Name: 'US Dollar',
    QuantityIncrement: 1e-8,
    Rolling24HrNotional: 0,
    Rolling24HrPxChange: 0,
    Rolling24HrPxChangePercent: 0,
    Rolling24HrVolume: 0,
    Rolling24NumTrades: 0,
    SelfTradePrevention: true,
    SessionClose: 0,
    SessionHigh: 0,
    SessionLow: 0,
    SessionOpen: 0,
    SessionStatus: 'Running',
    SessionStatusDateTime: '2023-04-03T20:45:28.461Z',
    SortIndex: 0,
    Symbol: 'OCN',
    TimeStamp: '0',
    VenueId: 1,
    VenueInstrumentId: 4,
    VenueSymbol: 'OCN',
    Volume: 0,
    MarginEnabled: false,
    MarginInitialRequirement: 0,
  },
  {
    AllowOnlyMarketMakerCounterParty: false,
    AskOrderCt: 0,
    AskQty: 0,
    BestBid: 0,
    BestOffer: 0,
    BidOrderCt: 0,
    BidQty: 0,
    CreateWithMarketRunning: true,
    CurrentDayNotional: 0,
    CurrentDayNumTrades: 0,
    CurrentDayPxChange: 0,
    CurrentDayVolume: 0,
    InstrumentId: 5,
    InstrumentType: 'Standard',
    IsDisable: false,
    LastTradeTime: 0,
    LastTradedPx: 0,
    LastTradedQty: 0,
    MasterDataId: 0,
    MinimumPrice: 0.01,
    MinimumQuantity: 1e-8,
    OMSId: 1,
    OtcConvertSizeEnabled: false,
    OtcConvertSizeThreshold: 0,
    OtcTradesPublic: true,
    PreviousSessionStatus: 'Unknown',
    PriceCeilingLimit: 0,
    PriceCeilingLimitEnabled: false,
    PriceCollarConvertToOtcAccountId: 0,
    PriceCollarConvertToOtcClientUserId: 0,
    PriceCollarConvertToOtcEnabled: false,
    PriceCollarConvertToOtcThreshold: 0,
    PriceCollarEnabled: false,
    PriceCollarIndexDifference: 0,
    PriceCollarPercent: 0,
    PriceCollarThreshold: 0,
    PriceFloorLimit: 0,
    PriceFloorLimitEnabled: false,
    PriceIncrement: 0.01,
    PriceTier: 0,
    Product1: 5,
    Product1Symbol: 'COOP',
    Product1Name: 'COOP',
    Product2: 1,
    Product2Symbol: 'USD',
    Product2Name: 'US Dollar',
    QuantityIncrement: 1e-8,
    Rolling24HrNotional: 0,
    Rolling24HrPxChange: 0,
    Rolling24HrPxChangePercent: 0,
    Rolling24HrVolume: 0,
    Rolling24NumTrades: 0,
    SelfTradePrevention: true,
    SessionClose: 0,
    SessionHigh: 0,
    SessionLow: 0,
    SessionOpen: 0,
    SessionStatus: 'Running',
    SessionStatusDateTime: '2023-04-03T20:46:30.025Z',
    SortIndex: 0,
    Symbol: 'COOP',
    TimeStamp: '0',
    VenueId: 1,
    VenueInstrumentId: 5,
    VenueSymbol: 'COOP',
    Volume: 0,
    MarginEnabled: false,
    MarginInitialRequirement: 0,
  },
];

type ComponentType = typeof MarketsList<(typeof data)[number]>;
type FilterOptionsProp = Exclude<
  React.ComponentProps<ComponentType>['filterOptions'],
  undefined
>;

const filterOptions: FilterOptionsProp = [
  { value: 1, label: 'USD' },
  { value: 2, label: 'BTC' },
  { value: 3, label: 'ETH' },
  { value: 6, label: 'THB' },
  { value: 5, label: 'COOP' },
  { value: 4, label: 'OCN' },
];

type Story = StoryObj<ComponentType>;

export default {
  title: 'products/MarketsList',
  component: MarketsList,
  argTypes: {
    ItemComponent: {
      control: false,
    },
    onSearch: {
      control: false,
    },
    onFilter: {
      control: false,
    },
    filters: {
      control: false,
    },
    searchText: {
      control: false,
    },
  },
  parameters: {
    layout: 'fullscreen',
  },
} as Meta<ComponentType>;

export const AssetMarketList: Story = {
  render({
    data: componentData,
    filterOptions: providedOptions,
    ItemComponent,
    withFilters,
    withSearch,
    onPress,
  }) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const props = useFilteredInstruments(componentData);
    return (
      <MarketsList
        {...props}
        filterOptions={providedOptions}
        ItemComponent={ItemComponent}
        withFilters={withFilters}
        withSearch={withSearch}
        onPress={onPress}
      />
    );
  },
  args: {
    data,
    filterOptions,
    ItemComponent: AssetListItem,
  },
};

export const MarginMarketList: Story = {
  ...AssetMarketList,
  args: {
    data,
    filterOptions: (
      [{ value: 'margin' as const, label: 'Margin' }] as FilterOptionsProp
    ).concat(filterOptions),
    ItemComponent: MarginListItem,
  },
};
