export const fiatSection = {
  title: 'Fiat Wallet',
  data: [
    {
      AccountId: 10,
      Amount: 860045.0570688058,
      DecimalPlaces: 2,
      DepositEnabled: true,
      Hold: 16823.11,
      IsDisabled: false,
      MarginEnabled: false,
      MasterDataUniqueProductSymbol: '',
      NoFees: false,
      NotionalDecimalPlaces: 2,
      NotionalHoldAmount: 16823.11,
      NotionalProductId: 1,
      NotionalProductSymbol: 'USD',
      NotionalRate: 1,
      NotionalValue: 860045.0570688058,
      OMSId: 1,
      PendingDeposits: 0,
      PendingWithdraws: 0,
      Product: 'USD',
      ProductFullName: 'US Dollar',
      ProductId: 1,
      ProductSymbol: 'USD',
      ProductType: 'NationalCurrency' as const,
      TickSize: 0.01,
      TotalDayDepositNotional: 0,
      TotalDayDeposits: 0,
      TotalDayTransferNotional: 0,
      TotalDayWithdrawNotional: 0,
      TotalDayWithdraws: 0,
      TotalMonthDepositNotional: 0,
      TotalMonthDeposits: 0,
      TotalMonthWithdrawNotional: 0,
      TotalMonthWithdraws: 0,
      TotalYearDepositNotional: 0,
      TotalYearDeposits: 0,
      TotalYearWithdrawNotional: 0,
      TotalYearWithdraws: 0,
      WithdrawEnabled: true,
      AvailableBalance: 0,
    },
  ],
};

export const ocnWalletItem = {
  AccountId: 1,
  Amount: 1000000,
  DecimalPlaces: 0,
  Hold: 0,
  IsDisabled: false,
  MarginEnabled: false,
  MasterDataUniqueProductSymbol: '',
  NoFees: true,
  NotionalDecimalPlaces: 2,
  NotionalHoldAmount: 0,
  NotionalProductId: 1,
  NotionalProductSymbol: 'USD',
  NotionalRate: 1,
  NotionalValue: 1000000,
  OMSId: 1,
  PendingDeposits: 0,
  PendingWithdraws: 0,
  Product: 'OCN',
  ProductFullName: 'OilCoin',
  ProductId: 3,
  ProductSymbol: 'OCN',
  ProductType: 'CryptoCurrency' as const,
  TickSize: 1,
  TotalDayDepositNotional: 0,
  TotalDayDeposits: 0,
  TotalDayWithdrawNotional: 0,
  TotalDayWithdraws: 0,
  TotalMonthDepositNotional: 0,
  TotalMonthDeposits: 0,
  TotalMonthWithdrawNotional: 0,
  TotalMonthWithdraws: 0,
  TotalYearDepositNotional: 0,
  TotalYearDeposits: 0,
  TotalYearWithdrawNotional: 0,
  TotalYearWithdraws: 0,
  AvailableBalance: 0,
};

export const cryptoSection = {
  title: 'Crypto Wallets',
  data: [
    {
      AccountId: 10,
      Amount: 860045.0570688058,
      DecimalPlaces: 2,
      DepositEnabled: true,
      Hold: 16823.11,
      IsDisabled: false,
      MarginEnabled: false,
      MasterDataUniqueProductSymbol: '',
      NoFees: false,
      NotionalDecimalPlaces: 2,
      NotionalHoldAmount: 16823.11,
      NotionalProductId: 1,
      NotionalProductSymbol: 'USD',
      NotionalRate: 1,
      NotionalValue: 860045.0570688058,
      OMSId: 1,
      PendingDeposits: 0,
      PendingWithdraws: 0,
      Product: 'USD',
      ProductFullName: 'US Dollar',
      ProductId: 1,
      ProductSymbol: 'USD',
      ProductType: 'NationalCurrency' as const,
      TickSize: 0.01,
      TotalDayDepositNotional: 0,
      TotalDayDeposits: 0,
      TotalDayTransferNotional: 0,
      TotalDayWithdrawNotional: 0,
      TotalDayWithdraws: 0,
      TotalMonthDepositNotional: 0,
      TotalMonthDeposits: 0,
      TotalMonthWithdrawNotional: 0,
      TotalMonthWithdraws: 0,
      TotalYearDepositNotional: 0,
      TotalYearDeposits: 0,
      TotalYearWithdrawNotional: 0,
      TotalYearWithdraws: 0,
      WithdrawEnabled: true,
      AvailableBalance: 0,
    },
    {
      AccountId: 10,
      Amount: 456.01292906,
      DecimalPlaces: 8,
      DepositEnabled: true,
      Hold: 1,
      IsDisabled: false,
      MarginEnabled: false,
      MasterDataUniqueProductSymbol: '',
      NoFees: false,
      NotionalDecimalPlaces: 2,
      NotionalHoldAmount: 27917,
      NotionalProductId: 1,
      NotionalProductSymbol: 'USD',
      NotionalRate: 27917,
      NotionalValue: 12730512.94056802,
      OMSId: 1,
      PendingDeposits: 0,
      PendingWithdraws: 0,
      Product: 'BTC',
      ProductFullName: 'Bitcoin',
      ProductId: 2,
      ProductSymbol: 'BTC',
      ProductType: 'CryptoCurrency' as const,
      TickSize: 1e-8,
      TotalDayDepositNotional: 0,
      TotalDayDeposits: 0,
      TotalDayTransferNotional: 0,
      TotalDayWithdrawNotional: 0,
      TotalDayWithdraws: 0,
      TotalMonthDepositNotional: 0,
      TotalMonthDeposits: 0,
      TotalMonthWithdrawNotional: 0,
      TotalMonthWithdraws: 0,
      TotalYearDepositNotional: 0,
      TotalYearDeposits: 0,
      TotalYearWithdrawNotional: 0,
      TotalYearWithdraws: 0,
      WithdrawEnabled: true,
      AvailableBalance: 0,
    },
    {
      AccountId: 10,
      Amount: 0,
      DecimalPlaces: 8,
      DepositEnabled: true,
      Hold: 0,
      IsDisabled: false,
      MarginEnabled: false,
      MasterDataUniqueProductSymbol: null,
      NoFees: false,
      NotionalDecimalPlaces: 2,
      NotionalHoldAmount: 0,
      NotionalProductId: 1,
      NotionalProductSymbol: 'USD',
      NotionalRate: 1903.3,
      NotionalValue: 0,
      OMSId: 1,
      PendingDeposits: 0,
      PendingWithdraws: 0,
      Product: 'ETH',
      ProductFullName: 'Ethereum',
      ProductId: 3,
      ProductSymbol: 'ETH',
      ProductType: 'CryptoCurrency' as const,
      TickSize: 1e-8,
      TotalDayDepositNotional: 0,
      TotalDayDeposits: 0,
      TotalDayTransferNotional: 0,
      TotalDayWithdrawNotional: 0,
      TotalDayWithdraws: 0,
      TotalMonthDepositNotional: 0,
      TotalMonthDeposits: 0,
      TotalMonthWithdrawNotional: 0,
      TotalMonthWithdraws: 0,
      TotalYearDepositNotional: 0,
      TotalYearDeposits: 0,
      TotalYearWithdrawNotional: 0,
      TotalYearWithdraws: 0,
      WithdrawEnabled: true,
      AvailableBalance: 0,
    },
    {
      AccountId: 10,
      Amount: 0,
      DecimalPlaces: 0,
      DepositEnabled: true,
      Hold: 0,
      IsDisabled: false,
      MarginEnabled: false,
      MasterDataUniqueProductSymbol: '',
      NoFees: false,
      NotionalDecimalPlaces: 2,
      NotionalHoldAmount: 0,
      NotionalProductId: 1,
      NotionalProductSymbol: 'USD',
      NotionalRate: 1,
      NotionalValue: 0,
      OMSId: 1,
      PendingDeposits: 0,
      PendingWithdraws: 0,
      Product: 'OCN',
      ProductFullName: 'Oil Coin',
      ProductId: 4,
      ProductSymbol: 'OCN',
      ProductType: 'CryptoCurrency' as const,
      TickSize: 1,
      TotalDayDepositNotional: 0,
      TotalDayDeposits: 0,
      TotalDayTransferNotional: 0,
      TotalDayWithdrawNotional: 0,
      TotalDayWithdraws: 0,
      TotalMonthDepositNotional: 0,
      TotalMonthDeposits: 0,
      TotalMonthWithdrawNotional: 0,
      TotalMonthWithdraws: 0,
      TotalYearDepositNotional: 0,
      TotalYearDeposits: 0,
      TotalYearWithdrawNotional: 0,
      TotalYearWithdraws: 0,
      WithdrawEnabled: true,
      AvailableBalance: 0,
    },
  ],
};
